### ISSUE TITLE
[BUG] Using the mod in 1.19.4 crashes the game

### ISSUE THREAD

**Issue by YaCCBoy** [tr7zw/ItemSwapper#141]
### Version information

itemswapper-fabric-0.3.2-mc1.19.3

### Expected Behavior

The mod should work correctly

### Actual Behavior

It crashes the game instead

### Reproduction Steps

1. Press the hotkey in a world
2. Observe as the game crashes

### Render engine

- [ ] Vanilla
- [X] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

### Crash report

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-03-31 21:30:39
Description: Rendering overlay

java.lang.NoSuchFieldError: field_4730
	at dev.tr7zw.itemswapper.overlay.ItemListOverlay.method_25394(ItemListOverlay.java:92)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.tr7zw.itemswapper.overlay.ItemListOverlay.method_25394(ItemListOverlay.java:92)

-- Overlay render details --
Details:
	Overlay name: dev.tr7zw.itemswapper.overlay.ItemListOverlay
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Affected level --
Details:
	All players: 1 total; [class_746['CarotteAtomique'/419, l='ClientLevel', x=-5998.25, y=80.06, z=-505.25]]
	Chunk stats: 1024, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,62,0), Section: (at 0,14,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 215687236 game time, 174734179 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Carottepack 0.4.0, file/Carottepack+ 0.4.0, Fabric Mods, resourcePack.continuity.default.name, resourcePack.continuity.glass_pane_culling_fix.name, itemswapper/default

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 793436288 bytes (756 MiB) / 2044723200 bytes (1950 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-1240P
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x46a6
	Graphics card #0 versionInfo: DriverVersion=31.0.101.3959
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17116.49
	Virtual memory used (MB): 13623.20
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 137.57
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.41
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.41
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.41
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.41
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.41
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.41
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.41
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.41
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.41
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.41
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.41
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.41
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.41
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.41
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.41
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.41
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.41
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.41
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.41
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.41
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cem: Custom Entity Models 0.7.3
			completeconfig-base: completeconfig-base 2.3.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.3.1
		clickthrough: ClickThrough 1.19.3-fabric0.68.1-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		collective: Collective 6.54
		continuity: Continuity 3.0.0-beta.2+1.19.3
		entity_texture_features: Entity Texture Features 4.3.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		exordium: Exordium 1.0.3-mc1.19.4
		fabric-api: Fabric API 0.76.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.52+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.5+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.22+ca5f59aaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.39+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.6+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.2+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.18+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.18
		fastload: Fast Load 2.6.11
		ferritecore: FerriteCore 5.2.0
		guiclock: GUI Clock 4.2
		immediatelyfast: ImmediatelyFast 1.1.11
			net_lenni0451_reflect: Reflect 1.1.0
		indium: Indium 1.0.15+mc1.19.4
		inventoryprofilesnext: Inventory Profiles Next 1.9.4
		itemswapper: ItemSwapper 0.3.2-mc1.19.3
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		libipn: libIPN 2.0.4
		litematica: Litematica 0.14.2
		lithium: Lithium 0.11.1
		malilib: MaLiLib 0.15.2
		memoryleakfix: Memory Leak Fix 1.0.0-beta.7
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.5
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.1.0-rc.4
		moreculling: More Culling 1.19.4-0.17.0
			conditional-mixin: conditional mixin 0.3.2
		nochatreports: No Chat Reports 1.19.4-v2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		shulkerboxtooltip: Shulker Box Tooltip 3.2.5+1.19.4
			cloth-config: Cloth Config v10 10.0.96
				cloth-basic-math: cloth-basic-math 0.6.1
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		vmp: Very Many Players 0.2.0+beta.7.68
		worldedit: WorldEdit 7.2.14+6360-094b734
		yet-another-config-lib: YetAnotherConfigLib 2.3.1
		zoomify: Zoomify 2.9.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.3.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.6
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 31.0.101.3959, Intel
	Window size: 2256x1398
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Carottepack 0.4.0, file/Carottepack+ 0.4.0, fabric, continuity:default (incompatible), continuity:glass_pane_culling_fix (incompatible), itemswapper:default (incompatible)
	Current Language: fr_ca
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-1240P
```

**Comment by tr7zw** [comment]
That's the 1.19.3 Version.
