### ISSUE TITLE
Litematica easyplaceMode & ItemSwapper

### ISSUE THREAD

**Issue by Astronomy20** [tr7zw/ItemSwapper#183]
Hello, I wanted to know if it's possible to use the easyplaceMode of Litematica without having items directly in the inventory but in Shulker boxes using this mod, and if it can be done, how do you do it?

Thank you to anyone who will respond.

**Comment by tr7zw** [comment]
Since itemswapper *swaps* items, there is no logic for taking single blocks from stacks out of shulkers. For now, this is not planned.

**Comment by mv-stns** [comment]
Hey there @tr7zw I didnt want to create a new issue since i think this fits pretty good in here. I'm on macOS and im not able to retrieve ANY items form shulkers when trying to build schematics. Is there any place that explains that feature?

**Comment by mv-stns** [comment]
What is the purpose of the Shulker Box feature? I'm confused because it cannot pull any items out of it.

**Comment by tr7zw** [comment]
You need to be in singleplayer or on a server that supports ItemSwapper. Then you can use pickblock/a palette/the itemswapper inventory screen to access items that are in shulkers.

**Comment by Astronomy20** [comment]
I resolved with another mod: [Take It Out](https://modrinth.com/plugin/takeitout)

**Comment by tr7zw** [comment]
Bit weird that someone spent time recoding ItemSwapper instead of just making a PR to add the logic for easyplace mode here.

**Comment by mv-stns** [comment]
Unfortunately my server crashes for some reason
```bash
[12:04:47] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_310
	at knot/dev.tr7zw.itemswapper.util.NMSHelper.<clinit>(NMSHelper.java:46) ~[itemswapper-fabric-0.7.5-mc1.21.3.jar:?]
	at knot/dev.tr7zw.itemswapper.packets.ShulkerSupportPayload.<clinit>(ShulkerSupportPayload.java:17) ~[itemswapper-fabric-0.7.5-mc1.21.3.jar:?]
	at knot/dev.tr7zw.itemswapper.server.ItemSwapperSharedServer.lambda$onLoad$12(ItemSwapperSharedServer.java:24) ~[itemswapper-fabric-0.7.5-mc1.21.3.jar:?]
	at knot/net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$0(ServerPlayConnectionEvents.java:37) ~[fabric-networking-api-v1-4.3.5+fd37071f40-32793e6922bf5a0e.jar:?]
	at knot/net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeInitEvent(ServerPlayNetworkAddon.java:59) ~[fabric-networking-api-v1-4.3.5+fd37071f40-32793e6922bf5a0e.jar:?]
	at knot/net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.lateInit(AbstractNetworkAddon.java:57) ~[fabric-networking-api-v1-4.3.5+fd37071f40-32793e6922bf5a0e.jar:?]
	at knot/net.minecraft.class_3244.handler$bjd002$fabric-networking-api-v1$initAddon(class_3244.java:2116) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.<init>(class_3244.java:263) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3324.redirect$zld000$carpet$replaceNetworkHandler(class_3324.java:2001) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3324.method_14570(class_3324.java:182) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:180) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:871) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:865) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:147) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:829) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:836) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:719) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 28 more
```

**Comment by mv-stns** [comment]
Do i need to install ItemSwapper server sided (fabric)

**Comment by tr7zw** [comment]
Yes, the newest release has a bug, download the fixed dev build from the actions tab to use on the server (or since you are on 1.21.3, you can use just the previous release on the server too).

**Comment by mv-stns** [comment]
thx alot! (Liebe Grüße und danke für die tolle Arbeit! Ich habe gerade herausgefunden, dass du ebenfalls aus DE bist. In naher Zukunft werde ich auch ein bisschen contributen)

**Comment by tr7zw** [comment]
Gerne 👍
