### ISSUE TITLE
[BUG] 1.20.4 Dedicated Server 

### ISSUE THREAD

**Issue by spocane** [tr7zw/ItemSwapper#206]
### Version information

itemswapper-fabric-0.6.0-mc1.20.4

### Other relevant installed mods

fabric-api-0.97.0+1.20.4

### Expected Behavior

Login to Server with mod installed on both Client and Server

### Actual Behavior

Crash with log error: 

`[17:09:55] [Server thread/ERROR]: Couldn't place player in world
java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_3324.handler$zij000$itemswapper$placeNewPlayer(class_3324.java:3011) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:282) ~[server-intermediary.jar:?]
        at net.minecraft.class_8610.method_52408(class_8610.java:128) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_53043(class_8736.java:20) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_11054(class_8736.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:757) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:09:55] [Server thread/INFO]: ******** lost connection: Invalid player data`

### Reproduction Steps

Join Server with mod installed on both

### Render engine

- [X] Vanilla
- [ ] Sodium(optionally with Iris)
- [ ] Optifine
- [ ] VulkanMod
- [ ] Canvas
- [ ] Other

**Comment by tr7zw** [comment]
Either you are missing the Fabric api on the server, or I messed something up.

**Comment by spocane** [comment]
Fabric API is on the server, Item Swapper works fine without the shulker support with it off the server and only on client.

Tested with Fabric Versions 0.15.7 and 0.15.10

only mods installed on client and server:

- fabric-api-0.97.0+1.20.4.jar
- itemswapper-fabric-0.6.0-mc1.20.4.jar

**Comment by tr7zw** [comment]
Then try downgrading the mod just on the server to the last version. Possible that I messed up something in the networking logic.

**Comment by spocane** [comment]
Correct, they are the Fabric Loader versions i tried testing with. the API is installed on both server and client.

With `itemswapper-fabric-0.5.6-mc1.20.4.jar` on server and `itemswapper-fabric-0.6.0-mc1.20.4.jar` on client it refuses to connect at all.

**Comment by tr7zw** [comment]
Ah I think I see what went wrong. I won't be able to fix that right now, spent the past 8 hours releasing versions and updating mods/plugins. 1.20.4 multiplayer you can just use the 0.5.6 version for now(but I heard something is off there too, networking sucks).

**Comment by spocane** [comment]
no problem, it works for my needs right now without it installed server side.

Thanks,

**Comment by tr7zw** [comment]
Oof I see what happened, I have the server and client util methods in the same class. oops. Will have to split that up.

**Comment by tr7zw** [comment]
Ok, turns out not only that is an issue, but something else also went horribly wrong. Time for an emergency fix before I go to bed 😅

**Comment by tr7zw** [comment]
Releasing at 3:30 am, what could go wrong. But there were a few things horribly wrong in all versions.
