### ISSUE TITLE
[CRASH] Crash with controlify 2.0

### ISSUE THREAD

**Issue by SettingDust** [tr7zw/ItemSwapper#207]
### Version information

0.6.1 fabric 1.20.1

### Other mods installed

controlify 2.0

### Reproduction Steps

Install them

### Crash Report file

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'controlify'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchFieldError: REGISTRY
	at dev.tr7zw.itemswapper.compat.ControlifyItemswapperEntrypoint.onControlifyPreInit(ControlifyItemswapperEntrypoint.java:27)
	at dev.isxander.controlify.Controlify.lambda$preInitialiseControlify$8(Controlify.java:150)
	at java.base@17.0.8/java.util.ArrayList.forEach(ArrayList.java:1511)
	at dev.isxander.controlify.Controlify.preInitialiseControlify(Controlify.java:148)
	at dev.isxander.controlify.ControlifyEntrypoint.onInitializeClient(ControlifyEntrypoint.java:8)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
```

**Comment by tr7zw** [comment]
The build was done for this Controlify version https://modrinth.com/mod/controlify/version/CzlyUU6C . Controlify 2.0 seems to have been released 3 days ago and contains breaking changes.
